cache:
  pip: true
  timeout: 1000

language: python

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      after_success:
        - poetry run coveralls
    - python: 3.8
      dist: xenial
      sudo: true

notifications:
  email: false

# repo branches to test
branches:
  - master
  - develop

before_install:
  - pip install --pre poetry==1.0.0b3

install:
  - poetry install

script:
  - poetry run pytest -- --cov jaeger --cov-report html
