cache:
  pip: true
  timeout: 1000

language: python

dist: xenial

jobs:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      after_success:
        - poetry run codecov
    - python: 3.8
      dist: xenial

notifications:
  email: false

# repo branches to test
branches:
  - master
  - develop
  - testing

before_install:
  - pip install poetry

install:
  - poetry install

  # This is needed due to a bug in CLU. Can be removed once we release a new version.
  - pip install --upgrade git+https://github.com/sdss/clu@master

script:
  - poetry run pytest
