cache:
  pip: true
  timeout: 1000

language: python

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      after_success:
        - coveralls
    - python: 3.8
      dist: xenial
      sudo: true

notifications:
  email: false

# repo branches to test
branches:
  - master
  - build-cleanup

install:
  - pip install -U pip wheel --quiet
  - pip install --upgrade setuptools --quiet
  - pip install pytest
  - pip install pytest-coverage
  - pip install coveralls
  - pip install .[dev]
  - pip install toml
  - pip install --pre --upgrade coverage


script:
  - pytest --cov jaeger --cov-report html
