ignore:
  - "python/jaeger/test/*"
  - "python/jaeger/bin/*"
  - "python/jaeger/etc/*"
  - "python/jaeger/core/logger.py"
  - "python/jaeger/core/color_print.py"
  - "python/jaeger/core/exceptions.py"
  - "*.py"
