on:
  push:
    tags:
      - '*'

name: Create Release

jobs:
  release:
    name: Build and publish

    runs-on: ubuntu-24.04

    permissions:
      contents: write
      id-token: write

    strategy:
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release
        uses: taiki-e/create-gh-release-action@v1
        with:
          title: jaeger $version
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install Python
        run: |
          uv python install 3.12

      - name: Build source and wheel
        run: |
          uv build --python 3.12

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
