on:
  push:
    tags:
      - '*'

name: Create Release

jobs:
  release:
    name: Build and publish

    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', 3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release
        uses: taiki-e/create-gh-release-action@v1
        if: ${{ matrix.python-version == '3.12' }}
        with:
          title: jaeger $version
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install Python
        run: |
          uv python install ${{ matrix.python-version }}

      - name: Build source and wheel
        if: ${{ matrix.python-version == '3.10' }}
        run: |
          uv build --python ${{ matrix.python-version }}

      - name: Build wheel
        if: ${{ matrix.python-version != '3.10' }}
        run: |
          uv build --wheel --python ${{ matrix.python-version }}

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
