# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    env:
      WOKCALIB_DIR: '/home/runner/work/jaeger/jaeger/fps_calibrations/apo/wok_calibs/sloanBase'
      PYTHONPATH: '/home/runner/work/jaeger/jaeger/fps_calibrations'
      OBSERVATORY: 'APO'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install --use-pep517 .

      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          python -m pip install ruff
          ruff .

      - name: Lint with black
        run: |
          python -m pip install black
          black --check python/
          black --check tests/

      - name: Test with pytest
        run: |
          python -m pip install pytest pytest-mock pytest-asyncio pytest-cov pyserial-asyncio
          pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
