# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    env:
      WOKCALIB_DIR: "/home/runner/work/jaeger/jaeger/fps_calibrations/apo/wok_calibs/sloanFlatCMM"
      PYTHONPATH: "/home/runner/work/jaeger/jaeger/fps_calibrations"

    steps:
      - uses: actions/checkout@v2

      - name: Cache Setup
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Clone fps_calibrations
        uses: actions/checkout@master
        with:
          repository: sdss/fps_calibrations
          path: fps_calibrations

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        uses: abatilo/actions-poetry@master

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          poetry install
          poetry run pip install git+https://github.com/csayres/kaiju

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          poetry run flake8 . --count --show-source --statistics

      - name: Lint with isort
        run: |
          poetry run isort -c python/

      - name: Lint with black
        run: |
          poetry run black --check .

      - name: Test with pytest
        run: |
          poetry run pytest

      - name: Upload coverage to Codecov
        if: matrix.python-version == '3.8'
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
